[global]
fsync period =0#操作系统自动刷新

[formats]
value = "%m"
full = "%d-%ms %V [%U][%L]:%m"  #2026-04-20 18:57:32-112 INFO [调用函数名][行数]:msg
[rules]
# mycat.DEBUG >stdout;simple
# mycat.ERROR >stdout;full #ERROR与FATAL日志会输出到标准输出中
mycat.INFO "./log/demo_log.log",5MB * 5 ~ "./log/demo_log-%d(%Y%m%d)_#2s.log";full
mycat.=DEBUG "./log/demo_log.log",5MB * 5 ~ "./log/demo_log.log-%d(%Y%m%d)_#2s";value #用于DEBUG时记录数据






